apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-backend
  template:
    metadata:
      labels:
        app: food-backend
    spec:
      containers:
      - name: backend
        image: yourdockerid/food-backend
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/fooddb"
---
apiVersion: v1
kind: Service
metadata:
  name: food-backend
spec:
  selector:
    app: food-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
